# Generated by Django 3.1 on 2020-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201129_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(max_length=30),
        ),
    ]
